replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi

persistence:
  enabled: false

antiAffinity: "soft"

esJavaOpts: "-Xmx512m -Xms512m"

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
    xpack.security.transport.ssl.enabled: false
    xpack.security.http.ssl.enabled: false

extraEnvs:
  - name: xpack.security.enabled
    value: "false"
  - name: xpack.security.http.ssl.enabled
    value: "false"
  - name: xpack.security.transport.ssl.enabled
    value: "false"

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 10
  successThreshold: 1
  exec:
    command:
      - bash
      - -c
      - curl -s http://localhost:9200/_cluster/health | grep -v '"status":"red"'