apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: resource-request-validator
webhooks:
- name: validate.resources.devops-case
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
  clientConfig:
    service:
      name: webhook-service
      namespace: default
      path: "/validate"
    caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURnakNDQW1xZ0F3SUJBZ0lVY2dxNS8wSTduRzZUamVhMDZyK3phZXo4MGVjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pqRWtNQ0lHQTFVRUF3d2JkMlZpYUc5dmF5MXpaWEoyYVdObExtUmxabUYxYkhRdWMzWmpNQjRYRFRJMgpNRFV4TlRFMU1UTTFNVm9YRFRJM01EVXhOVEUxTVRNMU1Wb3dKakVrTUNJR0ExVUVBd3diZDJWaWFHOXZheTF6ClpYSjJhV05sTG1SbFptRjFiSFF1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQXlNbys1VDV0ZlJuOSs3NWxuemtXVVZmSlQ5UHRwWCs3Y3ZNaGc1V0VmVE9oNlkzYk9zQm9hM1Z5T3ZjNApQNnB1cGlPaERCbmplalZvQXNONjNKb3BweXQ1QlMyalRCK3lEQmVxdE8vS2VCanhQVEEyVXhZeGxRSGM1TkRHCmc3OFNkMGNRZUNCNzVCeUk0SE55bnpnSGl3VWVqcG85RHVHRGVFbnUrRFQ0QWp4cW9LZXBMUWJsZE93ZHNheHAKWU4wWCticFA1TlRDMFZUQnhmVTFMTnl0QVFXalRDTmpiaEZuNS8xa2hBZkxWQUVmQkhpUXMzZnppMTdjMHBvVAowVDIwRElGVmw1ZjZCSlZYNnJnL1BmbjZBU1lKSzUyc3NTNkVHaHVuZzFLaVBoWm1PYWtESFF4VFNTUGkyT0szCk44RlFEWk54MEpHUENwMWk0M3NLQWNLMXdRSURBUUFCbzRHbk1JR2tNQjBHQTFVZERnUVdCQlErcXZ2cXpRT1oKWlhxVk9mdHpYSStMMUx0cDhUQWZCZ05WSFNNRUdEQVdnQlErcXZ2cXpRT1paWHFWT2Z0elhJK0wxTHRwOFRBUApCZ05WSFJNQkFmOEVCVEFEQVFIL01GRUdBMVVkRVFSS01FaUNHM2RsWW1odmIyc3RjMlZ5ZG1salpTNWtaV1poCmRXeDBMbk4yWTRJcGQyVmlhRzl2YXkxelpYSjJhV05sTG1SbFptRjFiSFF1YzNaakxtTnNkWE4wWlhJdWJHOWoKWVd3d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLYldjSnZBUWQyVmFZT0VJNTYrSTZoTHhkenhMNWV0UWxZYgp3SjNzdUhEYVVIR3hCSGNQeFRJd3JVK09veWhWQ1ZrZ0QxTFVQL0hRNDd6bG9FRFk1K0x5M3U2RVhKT0REY1J1CktiSlpwNmk4cFp3RlF5eDFob3B4MnJtTytOVXNUT0NMdlBRaXg4M0xZK0htZEl4MXhEblJHWnVDSm1TTHdheS8KNU1wdVJiRUw5aEl6Kzc2MmFnT0ZxSmx2alBXYWh4aERTbnFyakR4eUpLWmpoRU5qWXBzTDViM1hwSlNNRjFKTwptcVNBV1dBK2NCODlsbk41ZDZxbStXZENSQklZVlB1dVR4VkJKTkhPTFUvNzlYZzBtakNxZFBQZ05kMjFIS3dPClFocUUxaUZCT0NCRnYxcXh0NlVET0E1T2lzT3RmRmxoU1pud2NXeVVQZ1h2cUFsZVJjND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
  rules:
  - apiGroups: ["apps"]
    apiVersions: ["v1"]
    operations: ["CREATE", "UPDATE"]
    resources: ["deployments"]
  namespaceSelector:
    matchLabels:
      validate-resources: "true"